name: ocdb

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.7*
  #
  # production dependencies
  #
  - click
  - pyyaml
  - pandas
  - jupyterlab
  #
  # development dependencies
  #
  - httpretty
  - pytest
  - pytest-cov
  - flake8
  - ipython
