name: eocdb-client-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.6*
  #
  # runtime dependencies
  #
  - click =6.7
  - pyyaml =3.12
  #
  # development tools
  #
  - pytest =3.5.1
  - pytest-cov =2.5.1
  - flake8 =3.5.0
