name: eocdb-client-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.6*
  #
  # production dependencies
  #
  - click =7.0
  - pyyaml =3.12
  #
  # development dependencies
  #
  - httpretty =0.9.5
  - pytest =3.5.1
  - pytest-cov =2.5.1
  - flake8 =3.5.0
